# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: gitpod/workspace-mysql
tasks:
  - init: ./install.sh
    command: echo 'Hey'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1426
    onOpen: open-preview
