image: gitpod/workspace-mysql
tasks:
  - init: |
      sudo apt-get update && sudo apt install -y tmux
      brew install gettext
      cd quickstart
      make create-persistence-db-tables
      make create-datasource-tables
      export DATASOURCE_MYSQL_HOST=localhost
      export PERSISTENCE_MYSQL_HOST=localhost
      ./gen_config.sh
      cp -r config ../thirdeye-pinot/
      cd ..
      ./install.sh bigquery cloudsql
      gp sync-done preparation
    command: |
      echo "Welcome to the TE dev env"
      echo "Run `tmux attach -t frontend` to attach to frontend terminal"
      echo "Run `tmux attach -t backend` to attach to backend terminal"
    openMode: tab-after

  - init: gp sync-await preparation
    command: tmux new-session -d -s frontend './run-frontend.sh'
    openMode: tab-after

  - init: gp sync-await preparation
    command: tmux new-session -d -s frontend './run-backend.sh'
    openMode: tab-after

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1426
    onOpen: open-preview

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - redhat.java